In [5]:
import numpy as np
from scipy import stats

In [6]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b = np.array([
    [3, 4, 5],dd
    [6, 7, 8]
])
print(b.sum())
print(b.min())
print(b.mean())
print(b.sum())
print(b.prod())
print(np.square(b))



33
3
5.5
33
20160
[[ 9 16 25]
 [36 49 64]]


In [26]:
# Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(c
    )

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
# HINT, you'll first need to make sure that the "c" variable 
#is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [47]:
# Exercise 2 - Determine the standard deviation of c.
c.std()



2.581988897471611

In [48]:
# Exercise 3 - Determine the variance of c.
print(c.var())

6.666666666666667


In [51]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)



(3, 3)

In [53]:
# Exercise 5 - Transpose c and print out transposed result.
ct = np.transpose(c)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)



array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [83]:
# Exercise 7 - Write the code necessary to sum up the 
# result of c times c transposed. Answer should be 261
print(c)

ct = np.transpose(c)

c_prod = np.prod(c)
print(c_prod)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
362880


In [74]:

print(np.sum(c_trans))

285


In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c 
# times c transposed. Answer should be 131681894400.




In [27]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)



array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [29]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)



array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [30]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [37]:
# Exercise 4 - Find all the negative numbers in d

np.tan([c>0])

array([[[1.558, 1.558, 1.558],
        [1.558, 1.558, 1.558],
        [1.558, 1.558, 1.558]]], dtype=float16)

In [36]:
# Exercise 5 - Find all the positive numbers in d
np.tan([c<0])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float16)

In [87]:
# Exercise 6 - Return an array of only the unique numbers in d.
c.asarray((unique()))


AttributeError: 'numpy.ndarray' object has no attribute 'values_counts'

In [15]:
# Exercise 7 - Determine how many unique numbers there are in d.



In [16]:
# Exercise 8 - Print out the shape of d.



In [17]:
# Exercise 9 - Transpose and then print out the shape of d.




In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2